### ISSUE TITLE
Add test mails service

### ISSUE THREAD

**Issue by littlerobinson** [Kiwize/FeedManager#6]
Add a container testing email in your app :

```yaml
  mail-testing:
    image: axllent/mailpit:v1.6
    container_name: news-feed-mail-testing
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - news-feed-network
```
